server:
  servlet:
    context-path: /api/file-service

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: ekza-files

file-converting:
  converterPath: "${HOME}/Downloads/FBX2glTF-darwin-x64"
  rawFilesFolder: "${HOME}/Downloads/raw"
  convertedFilesFolder: "${HOME}/Downloads/converted"

amazon:
  s3:
    bucket: "ekza"
    accessKey: ${AMAZON_S3_ACCESS_KEY}
    secretKey: ${AMAZON_S3_SECRET_KEY}
